# Introduction to python

## Data types and concatenation

In [1]:
height = 1.79 # Height in meters
weight = 68.7 # Weight in kilograms
bmi = weight / (height ** 2) # Calculating body mass index
day_in_week = 7
x = "Body mass index for the given height and weight is"
print(x + ' ' + str(bmi))

Body mass index for the given height and weight is 21.44127836209856


In [2]:
type(bmi)

float

## Python Lists

In [2]:
fam = [1.73, 1.68, 1.71, 1.89]
fam2 = ["Liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
fam
new_list = [fam, fam2]
print(new_list)
print(fam2[6]) # selecting elements from list
print(fam2[3:5])# slicing elements of list, end is not included

[[1.73, 1.68, 1.71, 1.89], ['Liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]]
dad
[1.68, 'mom']


In [4]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
print(areas[-1]) #return a value using negative index
print(areas[0:4]) # returns the first four elements, note element with index 4 is not inlcluded
print(areas[3] + areas[-3]) #return sum of kitchen and bedroom areas

9.5
['hallway', 11.25, 'kitchen', 18.0]
28.75


In [5]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
print(areas[0:6]) # slice the first six elements of the list
print(areas[-4:]) # slice the last 4 elements of the list

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [6]:
fam2 = ["Liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam2)
fam2[7] = 1.86
print(fam2)
fam2[0:2] = ["lisa", 1.74]
print(fam2)

['Liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['Liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]
['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]


In [7]:
print(fam2)
fam2_ext = fam2 + ["me", 1.79]
print(fam2_ext)
del(fam2_ext[2]) #note here that indexes of the elements will change after you delete the elements
print(fam2_ext)

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]
['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.79]
['lisa', 1.74, 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.79]


In [8]:
x = ['a','b','c','d']
# y = x
# print(y)
# y[1] = 'z'
# print(y)
print (x) # Note 'b' in x is also changed, that is because x is a reference to the list which was copied to y. So when you manipulate the list
# using y it changes the main list
# To avoid this you need to use the list function or use slicing to copy the values and not the reference
y= list(x)
y[1] = 'z'
print(y)
y = x[:]
y[1] = 'z'
print(y)
print(x)

['a', 'b', 'c', 'd']
['a', 'z', 'c', 'd']
['a', 'z', 'c', 'd']
['a', 'b', 'c', 'd']


In [9]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
print(areas)
areas[-1] = 10.50
areas[4] = "chill zone"
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [44]:
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0, "bedroom", 10.75, "bathroom", 10.50]
print(areas)
areas_1 = areas + ["poolhouse", 24.5]
print(areas_1)
areas_2 = areas_1 + ["garage", 15.45]
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


In [10]:
# Copying lists
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
print(areas)
areas_copy = areas
areas_copy[0] = 0.5
print(areas) # since areas_copy = areas only adds reference to original list, any change to new list will update the original one
# To avoid this make we use the list function or the cpy function
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
areas_copy2 = list(areas)
areas_copy[0] = 0.5
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]
[0.5, 18.0, 20.0, 10.75, 9.5]
[11.25, 18.0, 20.0, 10.75, 9.5]


## Python Functions

In [11]:
fam = [1.73, 1.68, 1.71, 1.89]
print(max(fam))
print(round(fam[2],1))
help(round)


1.89
1.7
Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [14]:
help(sorted)
fam = [1.28, 1.87, 1.63, 1.21, 1.52]
fam2 = [1.42, 1.35, 1.78, 1.11]
full = fam + fam2
print(full)
print(sorted(full, reverse=True))

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

[1.28, 1.87, 1.63, 1.21, 1.52, 1.42, 1.35, 1.78, 1.11]
[1.87, 1.78, 1.63, 1.52, 1.42, 1.35, 1.28, 1.21, 1.11]


## Methods
Methods are functions that are associated with a specific object

In [23]:
fam = ["Liz", 1.71, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam.index("mom"))
print(fam.count(1.71))

4
2


In [24]:
fam.append("Me")
fam.append(1.89)
fam

['Liz', 1.71, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'Me', 1.89]

## Packages

Packages are directory of python scripts which can be also considered as modules. E.g. Numpy to work with arrays, matplotlib for data visulization and sickit learn for machine learning

In [6]:
import numpy
numpy.array([1,2,3])

array([1, 2, 3])

Writing numpy (or other package names) all the time can be tiring. To solve this you can import the package with a different name and refer to it using the prefix you specify as below.

In [63]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

Using only a specific function from the package is also possible, as shown below. However this reduces the readability of the code as the script becomes longer

In [64]:
from numpy import array
array([1,2,3])
# you can make it easier to read by doing something like this
from numpy import array as nparray
nparray([1,2,3])

array([1, 2, 3])