# Numpy (Numeric Python)

## Basics Of Numpy

In [ ]:
import numpy as np

In [ ]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [ ]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [ ]:
bmi = np_weight/np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

Numpy arrays can contain only one type of data type. Note the output of the below code block contains all strings

In [ ]:
np.array([1.0, 'String', True])

array(['1.0', 'String', 'True'], dtype='<U32')

Numpy is just another data type in python. As such methods behave differently than other data types. Look at the example below where + operation results in appendment in lists while it does arithmetic addition in case of numpy array

In [ ]:
list1 = [1,2,3]
list2 = [1,2,3]
print(list1 + list2)
np_array1 = np.array(list1)
np_array2 = np.array(list2)
print(np_array1 + np_array2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


Other operations

In [ ]:
print(bmi)
print(bmi[1])
print(bmi > 23)
print(bmi [bmi < 23])

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
20.97505668934241
[False False False  True False]
[21.85171573 20.97505669 21.75028214 21.44127836]


## Numpy Array

In [ ]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d.shape # note this call on shape is an attribute call and not a method (no round brackets around shape)

(2, 5)

Subsetting

In [ ]:
print(np_2d[0][2]) # select row and then from row select the column
print(np_2d[0,2])

1.71
1.71


Selecting the height and weight of 2nd and 3rd person in the family

In [ ]:
np_2d
np_2d[:,1:3] # select all rows and column 1(index - 2nd persons) and 2(index - 3rd person)

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

## Summary statistics